version: 2.1

jobs:
  test-package:
    docker:
      - image: cimg/node:22.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - package-deps-{{ checksum "package-lock.json" }}
            - package-deps-{{ .Branch }}-
            - package-deps-main-
            - package-deps-
      - run:
          name: Run Package Tests
          command: .circleci/test-package.sh .
      - save_cache:
          key: package-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

  security-audit:
    docker:
      - image: cimg/node:22.9
    steps:
      - checkout
      - run:
          name: Security Audit
          command: .circleci/security-audit-npm.sh .

workflows:
  version: 2
  test:
    jobs:
      - test-package
      - security-audit
